// Array order = display order on the page.
// To rearrange vinyls, move entries up/down in this array.
export const vinylRecords = [
  {
    id: "nightcafe-turn",
    artist: "The Night Cafe",
    song: "Turn",
    cover: "/assets/aboutme/vinyls/The Night Cafe - Turn.webp",
    audioSrc: "/assets/aboutme/songs/The Night Cafe - Turn.mp3",
  },
  {
    id: "yussef-tidalwave",
    artist: "Yussef Dayes",
    song: "Tidal Wave — Live from Malibu",
    cover: "/assets/aboutme/vinyls/Yussef Dayes - Tidal Wave - Live from Malibu.webp",
    audioSrc: "/assets/aboutme/songs/Yussef Dayes - Tidal Wave - Live from Malibu.mp3",
  },
  {
    id: "nujabes-luvsic",
    artist: "Nujabes",
    song: "Luv(sic) pt3 (feat. Shing02)",
    cover: "/assets/aboutme/vinyls/Nujabes - Luv(sic) pt3 (feat.Shing02).webp",
    audioSrc: "/assets/aboutme/songs/Nujabes - Luv(sic) pt3 (feat.Shing02).mp3",
  },
  {
    id: "peachpit-outtahere",
    artist: "Peach Pit",
    song: "Outta Here",
    cover: "/assets/aboutme/vinyls/Peach Pit - Outta Here.webp",
    audioSrc: "/assets/aboutme/songs/Peach Pit - Outta Here.mp3",
  },
  {
    id: "simplyred-holdingback",
    artist: "Simply Red",
    song: "Holding Back the Years",
    cover: "/assets/aboutme/vinyls/Simply Red - Holding Back the Years.webp",
    audioSrc: "/assets/aboutme/songs/Simply Red - Holding Back the Years.mp3",
  },
  {
    id: "thecure-boysdontcry",
    artist: "The Cure",
    song: "Boys Don't Cry",
    cover: "/assets/aboutme/vinyls/The Cure - Boys dont cry.webp",
    audioSrc: "/assets/aboutme/songs/The Cure - Boys dont cry.mp3",
  },
  {
    id: "tomokoaran-midnight",
    artist: "Tomoko Aran",
    song: "Midnight Pretenders",
    cover: "/assets/aboutme/vinyls/Tomoko Aran - Midnight Pretenders.webp",
    audioSrc: "/assets/aboutme/songs/Tomoko Aran - Midnight Pretenders.mp3",
  },
  {
    id: "hyakkei-kagefumi",
    artist: "Hyakkei",
    song: "Kagefumi",
    cover: "/assets/aboutme/vinyls/Hyakkei - Kagefumi.webp",
    audioSrc: "/assets/aboutme/songs/Hyakkei - Kagefumi.mp3",
  },
  {
    id: "macdemarco-preoccupied",
    artist: "Mac Demarco",
    song: "Preoccupied",
    cover: "/assets/aboutme/vinyls/Mac Demarco - Preoccupied.webp",
    audioSrc: "/assets/aboutme/songs/Mac Demarco - Preoccupied.mp3",
  },
  {
    id: "sade-kissoflife",
    artist: "Sade",
    song: "Kiss of Life",
    cover: "/assets/aboutme/vinyls/Sade - Kiss of Life.webp",
    audioSrc: "/assets/aboutme/songs/Sade - Kiss of Life.mp3",
  },
  {
    id: "spandauballet-true",
    artist: "Spandau Ballet",
    song: "True",
    cover: "/assets/aboutme/vinyls/Spandau Ballet - True.webp",
    audioSrc: "/assets/aboutme/songs/Spandau Ballet - True.mp3",
  },
  {
    id: "pokemon-eternacity",
    artist: "Pokemon",
    song: "Eterna City (Night)",
    cover: "/assets/aboutme/vinyls/Pokemon - Eterna City (Night).webp",
    audioSrc: "/assets/aboutme/songs/Pokemon - Eterna City (Night).mp3",
  },
];
