// Array order = display order on the page.
// To rearrange vinyls, move entries up/down in this array.
export const vinylRecords = [
  {
    id: "nightcafe-turn",
    artist: "The Night Cafe",
    song: "Turn",
    cover: "/assets/aboutme/vinyls/The Night Cafe - Turn.webp",
    audioSrc: "/assets/aboutme/songs/The Night Cafe - Turn.mp3",
  },
  // {
  //   id: "yussef-tidalwave",
  //   artist: "Yussef Dayes",
  //   song: "Tidal Wave — Live from Malibu",
  //   cover: "/assets/aboutme/vinyls/Yussef Dayes - Tidal Wave - Live from Malibu.webp",
  //   audioSrc: "/assets/aboutme/songs/Yussef Dayes - Tidal Wave - Live from Malibu.mp3",
  // },
  // {
  //   id: "nujabes-luvsic",
  //   artist: "Nujabes",
  //   song: "Luv(sic) pt3 (feat. Shing02)",
  //   cover: "/assets/aboutme/vinyls/Nujabes - Luv(sic) pt3 (feat.Shing02).webp",
  //   audioSrc: "/assets/aboutme/songs/Nujabes - Luv(sic) pt3 (feat.Shing02).mp3",
  // },
  {
    id: "peachpit-outtahere",
    artist: "Peach Pit",
    song: "Outta Here",
    cover: "/assets/aboutme/vinyls/Peach Pit - Outta Here.webp",
    audioSrc: "/assets/aboutme/songs/Peach Pit - Outta Here.mp3",
  },
  {
    id: "simplyred-holdingback",
    artist: "Simply Red",
    song: "Holding Back the Years",
    cover: "/assets/aboutme/vinyls/Simply Red - Holding Back the Years.webp",
    audioSrc: "/assets/aboutme/songs/Simply Red - Holding Back the Years.mp3",
  },
  {
    id: "tylerthecreator-areweskillfriends",
    artist: "Tyler the Creator",
    song: "ARE WE STILL FRIENDS?",
    cover: "/assets/aboutme/vinyls/Tyler the Creator - ARE WE STILL FRIENDS_.webp",
    audioSrc: "/assets/aboutme/songs/Tyler the Creator - ARE WE STILL FRIENDS_.mp3",
  },
  // {
  //   id: "macdemarco-preoccupied",
  //   artist: "Mac Demarco",
  //   song: "Preoccupied",
  //   cover: "/assets/aboutme/vinyls/Mac Demarco - Preoccupied.webp",
  //   audioSrc: "/assets/aboutme/songs/Mac Demarco - Preoccupied.mp3",
  // },
  {
    id: "sade-kissoflife",
    artist: "Sade",
    song: "Kiss of Life",
    cover: "/assets/aboutme/vinyls/Sade - Kiss of Life.webp",
    audioSrc: "/assets/aboutme/songs/Sade - Kiss of Life.mp3",
  },
  {
    id: "spandauballet-true",
    artist: "Spandau Ballet",
    song: "True",
    cover: "/assets/aboutme/vinyls/Spandau Ballet - True.webp",
    audioSrc: "/assets/aboutme/songs/Spandau Ballet - True.mp3",
  },
  // {
  //   id: "pokemon-eternacity",
  //   artist: "Pokemon",
  //   song: "Eterna City (Night)",
  //   cover: "/assets/aboutme/vinyls/Pokemon - Eterna City (Night).webp",
  //   audioSrc: "/assets/aboutme/songs/Pokemon - Eterna City (Night).mp3",
  // },
  {
    id: "fcuckers-ifyouwanna",
    artist: "Fcuckers",
    song: "if you wanna party, come over to my house",
    cover: "/assets/aboutme/vinyls/Fcuckers - if you wanna party, come over to my house.webp",
    audioSrc: "/assets/aboutme/songs/Fcuckers - if you wanna party, come over to my house.mp3",
  },
  {
    id: "higherbrothers-popout",
    artist: "HIGHER BROTHERS",
    song: "Pop Out",
    cover: "/assets/aboutme/vinyls/HIGHER BROTHERS - Pop Out.webp",
    audioSrc: "/assets/aboutme/songs/HIGHER BROTHERS - Pop Out.mp3",
  },
  {
    id: "sesoneon-thewave",
    artist: "SE SO NEON",
    song: "The Wave",
    cover: "/assets/aboutme/vinyls/SE SO NEON - The Wave.webp",
    audioSrc: "/assets/aboutme/songs/SE SO NEON - The Wave.mp3",
  },
  {
    id: "titlefight-crescentshaped",
    artist: "Title Fight",
    song: "Crescent Shaped Depression",
    cover: "/assets/aboutme/vinyls/Title Fight - Crescent Shaped Depression.webp",
    audioSrc: "/assets/aboutme/songs/Title Fight - Crescent Shaped Depression.mp3",
  },
  {
    id: "bigbang-haruharu",
    artist: "BIGBANG",
    song: "Haru Haru",
    cover: "/assets/aboutme/vinyls/BIGBANG - Haru Haru.webp",
    audioSrc: "/assets/aboutme/songs/BIGBANG - Haru Haru.mp3",
  },
  {
    id: "neckdeep-december",
    artist: "Neck Deep",
    song: "December",
    cover: "/assets/aboutme/vinyls/Neck Deep - December.webp",
    audioSrc: "/assets/aboutme/songs/Neck Deep - December.mp3",
  },
];
